/**
 * DTCG token tree -> CSS custom properties, SCSS variables and typed TS.
 *
 * One emitter per target, each a pure `(tokens, options) => string`, so the
 * output can be snapshot-tested without touching the filesystem.
 */

import {
  walkTokens,
  resolveAliases,
  toKebabName,
  toCamelName,
  expandToken,
  isComposite,
  TYPOGRAPHY_PROPERTIES,
} from './dtcg.mjs';

const BANNER = '/* Generated by design-bridge. Do not edit by hand. */';

/** The custom-property name a token path gets, in the one place it is decided. */
function cssName(path, prefix) {
  return `--${prefix ? `${prefix}-` : ''}${toKebabName(path)}`;
}

/**
 * Emit CSS custom properties.
 *
 * Aliases are intentionally NOT resolved here: `--semantic-bg: var(--palette-slate-50)`
 * keeps the indirection alive in the browser, so overriding one palette token in
 * a theme block cascades to every semantic token that references it. That is the
 * whole point of theming with custom properties.
 */
export function toCss(tokens, { selector = ':root', prefix = '' } = {}) {
  const lines = [];
  for (const { path, token } of walkTokens(tokens)) {
    const alias = typeof token.$value === 'string' && /^\{[^}]+\}$/.test(token.$value.trim());
    if (token.$description) lines.push(`  /* ${token.$description} */`);
    if (alias) {
      lines.push(
        `  ${cssName(path, prefix)}: ` +
          `var(${cssName(token.$value.trim().slice(1, -1).split('.'), prefix)});`,
      );
      continue;
    }
    // A composite contributes more than one declaration; a scalar contributes
    // exactly one, with an empty suffix. Both go through the same loop.
    for (const { suffix, value } of expandToken(token, path)) {
      lines.push(`  ${cssName([...path, ...suffix], prefix)}: ${value};`);
    }
  }
  return `${BANNER}\n${selector} {\n${lines.join('\n')}\n}\n`;
}

/**
 * Emit a utility class per `typography` token.
 *
 * A type ramp is the one part of a design system that is a *set* of
 * declarations rather than a value, so it cannot be delivered as a custom
 * property alone — `font: var(--ds-text-body)` has no valid spelling. The class
 * references the properties instead of repeating their values, so a theme that
 * overrides `--ds-text-body-font-size` reaches every element using the class
 * without the stylesheet being rebuilt.
 */
export function toCssUtilities(tokens, { prefix = '', classPrefix = prefix } = {}) {
  const blocks = [];
  for (const { path, token } of walkTokens(tokens)) {
    if (token.$type !== 'typography' || !isComposite(token)) continue;
    const declarations = Object.entries(TYPOGRAPHY_PROPERTIES)
      .filter(([key]) => token.$value[key] !== undefined)
      .map(([key, property]) => `  ${property}: var(${cssName([...path, key], prefix)});`);
    if (!declarations.length) continue;
    const name = `.${classPrefix ? `${classPrefix}-` : ''}${toKebabName(path)}`;
    if (token.$description) blocks.push(`/* ${token.$description} */`);
    blocks.push(`${name} {\n${declarations.join('\n')}\n}`);
  }
  if (!blocks.length) return '';
  return `${BANNER}\n${blocks.join('\n\n')}\n`;
}

/**
 * Emit SCSS variables. Aliases ARE resolved: Sass resolves at compile time and
 * cannot follow a runtime `var()`, so leaving the reference would break themes.
 */
export function toScss(tokens, { prefix = '' } = {}) {
  const flat = resolveAliases(tokens);
  const lines = [];
  for (const { path, token } of walkTokens(flat)) {
    if (token.$description) lines.push(`// ${token.$description}`);
    for (const { suffix, value } of expandToken(token, path)) {
      const name = `$${prefix ? `${prefix}-` : ''}${toKebabName([...path, ...suffix])}`;
      lines.push(`${name}: ${value};`);
    }
  }
  return `${BANNER}\n${lines.join('\n')}\n`;
}

/**
 * Emit a typed TypeScript module.
 *
 * Values point at the CSS custom property rather than the literal, so a token
 * consumed from TS and one consumed from CSS always agree — including after a
 * runtime theme switch, which a baked-in literal would miss.
 */
export function toTypeScript(tokens, { prefix = '', constName = 'tokens' } = {}) {
  const entries = [];
  for (const { path, token } of walkTokens(tokens)) {
    const doc = token.$description ? `  /** ${token.$description} */\n` : '';
    for (const { suffix } of expandToken(token, path)) {
      const full = [...path, ...suffix];
      entries.push(`${doc}  ${toCamelName(full)}: 'var(${cssName(full, prefix)})',`);
    }
  }
  return [
    '// Generated by design-bridge. Do not edit by hand.',
    `export const ${constName} = {`,
    entries.join('\n'),
    '} as const;',
    '',
    `export type TokenName = keyof typeof ${constName};`,
    '',
  ].join('\n');
}

/** Emit the flat `{ name: literal }` map, useful for tests and documentation. */
export function toFlatJson(tokens, { prefix = '' } = {}) {
  const flat = resolveAliases(tokens);
  const output = {};
  for (const { path, token } of walkTokens(flat)) {
    for (const { suffix, value } of expandToken(token, path)) {
      output[`${prefix ? `${prefix}-` : ''}${toKebabName([...path, ...suffix])}`] = value;
    }
  }
  return `${JSON.stringify(output, null, 2)}\n`;
}
