/**
 * DTCG token tree -> CSS custom properties, SCSS variables and typed TS.
 *
 * One emitter per target, each a pure `(tokens, options) => string`, so the
 * output can be snapshot-tested without touching the filesystem.
 */

import { walkTokens, resolveAliases, toKebabName, toCamelName, formatValue } from './dtcg.mjs';

const BANNER = '/* Generated by design-bridge. Do not edit by hand. */';

/**
 * Emit CSS custom properties.
 *
 * Aliases are intentionally NOT resolved here: `--semantic-bg: var(--palette-slate-50)`
 * keeps the indirection alive in the browser, so overriding one palette token in
 * a theme block cascades to every semantic token that references it. That is the
 * whole point of theming with custom properties.
 */
export function toCss(tokens, { selector = ':root', prefix = '' } = {}) {
  const lines = [];
  for (const { path, token } of walkTokens(tokens)) {
    const name = `--${prefix ? `${prefix}-` : ''}${toKebabName(path)}`;
    const alias = typeof token.$value === 'string' && /^\{[^}]+\}$/.test(token.$value.trim());
    const value = alias
      ? `var(--${prefix ? `${prefix}-` : ''}${toKebabName(token.$value.trim().slice(1, -1).split('.'))})`
      : formatValue(token, path);
    if (token.$description) lines.push(`  /* ${token.$description} */`);
    lines.push(`  ${name}: ${value};`);
  }
  return `${BANNER}\n${selector} {\n${lines.join('\n')}\n}\n`;
}

/**
 * Emit SCSS variables. Aliases ARE resolved: Sass resolves at compile time and
 * cannot follow a runtime `var()`, so leaving the reference would break themes.
 */
export function toScss(tokens, { prefix = '' } = {}) {
  const flat = resolveAliases(tokens);
  const lines = [];
  for (const { path, token } of walkTokens(flat)) {
    const name = `$${prefix ? `${prefix}-` : ''}${toKebabName(path)}`;
    if (token.$description) lines.push(`// ${token.$description}`);
    lines.push(`${name}: ${formatValue(token, path)};`);
  }
  return `${BANNER}\n${lines.join('\n')}\n`;
}

/**
 * Emit a typed TypeScript module.
 *
 * Values point at the CSS custom property rather than the literal, so a token
 * consumed from TS and one consumed from CSS always agree — including after a
 * runtime theme switch, which a baked-in literal would miss.
 */
export function toTypeScript(tokens, { prefix = '', constName = 'tokens' } = {}) {
  const entries = [];
  for (const { path, token } of walkTokens(tokens)) {
    const cssVar = `--${prefix ? `${prefix}-` : ''}${toKebabName(path)}`;
    const doc = token.$description ? `  /** ${token.$description} */\n` : '';
    entries.push(`${doc}  ${toCamelName(path)}: 'var(${cssVar})',`);
  }
  return [
    '// Generated by design-bridge. Do not edit by hand.',
    `export const ${constName} = {`,
    entries.join('\n'),
    '} as const;',
    '',
    `export type TokenName = keyof typeof ${constName};`,
    '',
  ].join('\n');
}

/** Emit the flat `{ name: literal }` map, useful for tests and documentation. */
export function toFlatJson(tokens, { prefix = '' } = {}) {
  const flat = resolveAliases(tokens);
  const output = {};
  for (const { path, token } of walkTokens(flat)) {
    output[`${prefix ? `${prefix}-` : ''}${toKebabName(path)}`] = formatValue(token, path);
  }
  return `${JSON.stringify(output, null, 2)}\n`;
}
