#!/usr/bin/env node
/**
 * design-bridge-tokens — pull Figma Variables and build platform artefacts.
 *
 *   design-bridge-tokens pull  --file <key> [--out tokens/]
 *   design-bridge-tokens build --in tokens/ --out dist/ [--prefix ds]
 *
 * The token itself is read from FIGMA_TOKEN and never accepted as a flag, so it
 * cannot leak into shell history, CI logs or a process listing.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fetchLocalVariables, variablesToTokens } from './figma-variables.mjs';
import { toCss, toScss, toTypeScript, toFlatJson } from './build.mjs';

function parseArgs(argv) {
  const [command, ...rest] = argv;
  const flags = {};
  for (let i = 0; i < rest.length; i += 1) {
    if (!rest[i].startsWith('--')) continue;
    const key = rest[i].slice(2);
    const next = rest[i + 1];
    if (next === undefined || next.startsWith('--')) {
      flags[key] = true;
    } else {
      flags[key] = next;
      i += 1;
    }
  }
  return { command, flags };
}

function slug(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function pull(flags) {
  const fileKey = flags.file ?? process.env.FIGMA_FILE_KEY;
  const token = process.env.FIGMA_TOKEN;
  if (!fileKey) throw new Error('Missing --file <key> (or FIGMA_FILE_KEY).');
  if (!token) throw new Error('Missing FIGMA_TOKEN environment variable.');

  const outDir = path.resolve(flags.out ?? 'tokens');
  const payload = await fetchLocalVariables({ fileKey, token });
  const byCollection = variablesToTokens(payload);

  fs.mkdirSync(outDir, { recursive: true });
  let written = 0;
  for (const [collection, modes] of Object.entries(byCollection)) {
    for (const [mode, tokens] of Object.entries(modes)) {
      const file = path.join(outDir, `${slug(collection)}.${slug(mode)}.tokens.json`);
      fs.writeFileSync(file, `${JSON.stringify(tokens, null, 2)}\n`);
      console.log(`  wrote ${path.relative(process.cwd(), file)}`);
      written += 1;
    }
  }
  console.log(`Pulled ${written} token file(s) from Figma file ${fileKey}.`);
}

/** `palette.dark.tokens.json` -> `{ collection: 'palette', mode: 'dark' }`. */
function describe(fileName) {
  const parts = fileName.replace(/\.tokens\.json$/, '').split('.');
  return { collection: parts[0], mode: parts[1] ?? 'default' };
}

function build(flags) {
  const inDir = path.resolve(flags.in ?? 'tokens');
  const outDir = path.resolve(flags.out ?? 'dist/tokens');
  const prefix = flags.prefix === true ? '' : (flags.prefix ?? '');
  const defaultMode = flags['default-mode'] ?? 'light';

  const files = fs.readdirSync(inDir).filter((name) => name.endsWith('.tokens.json')).sort();
  if (files.length === 0) throw new Error(`No *.tokens.json files found in ${inDir}`);

  // The default mode must be emitted first. It owns `:root`, and every other
  // mode overrides it; relying on selector specificity to fix a wrong order
  // works by accident and breaks as soon as a mode uses a bare selector.
  files.sort((a, b) => {
    const rank = (name) => (['default', defaultMode].includes(describe(name).mode) ? 0 : 1);
    return rank(a) - rank(b) || a.localeCompare(b);
  });
  fs.mkdirSync(outDir, { recursive: true });

  const cssBlocks = [];
  for (const file of files) {
    const { collection, mode } = describe(file);
    const tokens = JSON.parse(fs.readFileSync(path.join(inDir, file), 'utf8'));

    // The default mode owns `:root`; every other mode is emitted twice, as a
    // `[data-theme]` opt-in and inside a `prefers-color-scheme` query, so the
    // theme follows the OS unless the page explicitly pins it.
    if (mode === defaultMode || mode === 'default') {
      cssBlocks.push(toCss(tokens, { selector: ':root', prefix }));
    } else {
      cssBlocks.push(toCss(tokens, { selector: `:root[data-theme="${mode}"]`, prefix }));
      if (mode === 'dark') {
        const block = toCss(tokens, { selector: ':root:not([data-theme="light"])', prefix });
        cssBlocks.push(`@media (prefers-color-scheme: dark) {\n${block}}\n`);
      }
    }

    const base = `${collection}.${mode}`;
    fs.writeFileSync(path.join(outDir, `${base}.scss`), toScss(tokens, { prefix }));
    fs.writeFileSync(path.join(outDir, `${base}.ts`), toTypeScript(tokens, { prefix }));
    fs.writeFileSync(path.join(outDir, `${base}.flat.json`), toFlatJson(tokens, { prefix }));
  }

  // One banner for the whole stylesheet, not one per block.
  const stripped = cssBlocks.map((block) => block.replace(/^\/\* Generated by design-bridge[^\n]*\n/gm, ''));
  const css = `/* Generated by design-bridge. Do not edit by hand. */\n${stripped.join('\n')}`;
  fs.writeFileSync(path.join(outDir, 'tokens.css'), css);
  console.log(`Built ${files.length} token file(s) into ${path.relative(process.cwd(), outDir)}.`);
}

const { command, flags } = parseArgs(process.argv.slice(2));
try {
  if (command === 'pull') await pull(flags);
  else if (command === 'build') build(flags);
  else {
    console.log('Usage: design-bridge-tokens <pull|build> [--file key] [--in dir] [--out dir] [--prefix ds]');
    process.exit(command ? 1 : 0);
  }
} catch (error) {
  console.error(`design-bridge-tokens: ${error.message}`);
  process.exit(1);
}
