#!/usr/bin/env node
/**
 * design-bridge-tokens — pull Figma Variables and build platform artefacts.
 *
 *   design-bridge-tokens pull  --file <key> [--out tokens/] [--no-styles]
 *   design-bridge-tokens build --in tokens/ --out dist/ [--prefix ds]
 *
 * `pull` brings across both halves of a design system. Variables carry the
 * values a system names; Styles carry the ones it composes — a shadow, a type
 * ramp, a layout grid. They come from different endpoints and land in the same
 * token directory, because on the code side there is no such distinction.
 *
 * The token itself is read from FIGMA_TOKEN and never accepted as a flag, so it
 * cannot leak into shell history, CI logs or a process listing.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fetchLocalVariables, variablesToTokens } from './figma-variables.mjs';
import { pullStyles } from './figma-styles.mjs';
import { toCss, toCssUtilities, toScss, toTypeScript, toFlatJson } from './build.mjs';

function parseArgs(argv) {
  const [command, ...rest] = argv;
  const flags = {};
  for (let i = 0; i < rest.length; i += 1) {
    if (!rest[i].startsWith('--')) continue;
    const key = rest[i].slice(2);
    const next = rest[i + 1];
    if (next === undefined || next.startsWith('--')) {
      flags[key] = true;
    } else {
      flags[key] = next;
      i += 1;
    }
  }
  return { command, flags };
}

function slug(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function pull(flags) {
  const fileKey = flags.file ?? process.env.FIGMA_FILE_KEY;
  const token = process.env.FIGMA_TOKEN;
  if (!fileKey) throw new Error('Missing --file <key> (or FIGMA_FILE_KEY).');
  if (!token) throw new Error('Missing FIGMA_TOKEN environment variable.');

  const outDir = path.resolve(flags.out ?? 'tokens');
  const payload = await fetchLocalVariables({ fileKey, token });
  const byCollection = variablesToTokens(payload);

  fs.mkdirSync(outDir, { recursive: true });
  let written = 0;
  for (const [collection, modes] of Object.entries(byCollection)) {
    for (const [mode, tokens] of Object.entries(modes)) {
      const file = path.join(outDir, `${slug(collection)}.${slug(mode)}.tokens.json`);
      fs.writeFileSync(file, `${JSON.stringify(tokens, null, 2)}\n`);
      console.log(`  wrote ${path.relative(process.cwd(), file)}`);
      written += 1;
    }
  }
  // Styles are a separate endpoint and a separate failure: a file can have
  // Variables and no Styles, or an account can reach one and not the other.
  // Losing the variables that were already fetched because of that would be a
  // poor trade, so this half reports and continues.
  if (flags.styles !== false && flags['no-styles'] !== true) {
    try {
      const { tokens, skipped } = await pullStyles({ fileKey, token });
      for (const [group, tree] of Object.entries(tokens)) {
        const file = path.join(outDir, `${slug(group)}.default.tokens.json`);
        fs.writeFileSync(file, `${JSON.stringify(tree, null, 2)}\n`);
        console.log(`  wrote ${path.relative(process.cwd(), file)}`);
        written += 1;
      }
      for (const entry of skipped) {
        console.warn(`  skipped ${entry.type} style "${entry.name}": nothing a token can express`);
      }
    } catch (error) {
      console.warn(`  styles not pulled: ${error.message}`);
    }
  }

  console.log(`Pulled ${written} token file(s) from Figma file ${fileKey}.`);
}

/** `palette.dark.tokens.json` -> `{ collection: 'palette', mode: 'dark' }`. */
/**
 * Split a generated utility sheet into its individual rules, keyed by selector.
 * The banner comment is dropped: the assembled sheet carries its own.
 */
function splitRules(sheet) {
  if (!sheet) return [];
  return sheet
    .replace(/^\/\* Generated by design-bridge[^\n]*\n/gm, '')
    .split(/(?<=\})\n+/)
    .map((text) => text.trim())
    .filter(Boolean)
    .map((text) => ({ selector: text.slice(0, text.indexOf('{')).trim(), text: `${text}\n` }));
}

function describe(fileName) {
  const parts = fileName.replace(/\.tokens\.json$/, '').split('.');
  return { collection: parts[0], mode: parts[1] ?? 'default' };
}

function build(flags) {
  const inDir = path.resolve(flags.in ?? 'tokens');
  const outDir = path.resolve(flags.out ?? 'dist/tokens');
  const prefix = flags.prefix === true ? '' : (flags.prefix ?? '');
  const defaultMode = flags['default-mode'] ?? 'light';

  const files = fs.readdirSync(inDir).filter((name) => name.endsWith('.tokens.json')).sort();
  if (files.length === 0) throw new Error(`No *.tokens.json files found in ${inDir}`);

  // The default mode must be emitted first. It owns `:root`, and every other
  // mode overrides it; relying on selector specificity to fix a wrong order
  // works by accident and breaks as soon as a mode uses a bare selector.
  files.sort((a, b) => {
    const rank = (name) => (['default', defaultMode].includes(describe(name).mode) ? 0 : 1);
    return rank(a) - rank(b) || a.localeCompare(b);
  });
  fs.mkdirSync(outDir, { recursive: true });

  const cssBlocks = [];
  const utilityRules = new Map();
  for (const file of files) {
    const { collection, mode } = describe(file);
    const tokens = JSON.parse(fs.readFileSync(path.join(inDir, file), 'utf8'));

    // The default mode owns `:root`; every other mode is emitted twice, as a
    // `[data-theme]` opt-in and inside a `prefers-color-scheme` query, so the
    // theme follows the OS unless the page explicitly pins it.
    if (mode === defaultMode || mode === 'default') {
      cssBlocks.push(toCss(tokens, { selector: ':root', prefix }));
    } else {
      cssBlocks.push(toCss(tokens, { selector: `:root[data-theme="${mode}"]`, prefix }));
      if (mode === 'dark') {
        const block = toCss(tokens, { selector: ':root:not([data-theme="light"])', prefix });
        cssBlocks.push(`@media (prefers-color-scheme: dark) {\n${block}}\n`);
      }
    }

    // Typography is the one kind of token that is a set of declarations rather
    // than a value, so it also leaves as classes. The rules reference the
    // custom properties rather than repeating their values, which is exactly
    // what makes them mode-independent -- so a class is kept once, from
    // whichever mode declared it first, instead of once per mode.
    for (const rule of splitRules(toCssUtilities(tokens, { prefix }))) {
      if (!utilityRules.has(rule.selector)) utilityRules.set(rule.selector, rule.text);
    }

    const base = `${collection}.${mode}`;
    fs.writeFileSync(path.join(outDir, `${base}.scss`), toScss(tokens, { prefix }));
    fs.writeFileSync(path.join(outDir, `${base}.ts`), toTypeScript(tokens, { prefix }));
    fs.writeFileSync(path.join(outDir, `${base}.flat.json`), toFlatJson(tokens, { prefix }));
  }

  // One banner for the whole stylesheet, not one per block.
  const stripped = cssBlocks.map((block) => block.replace(/^\/\* Generated by design-bridge[^\n]*\n/gm, ''));
  const css = `/* Generated by design-bridge. Do not edit by hand. */\n${stripped.join('\n')}`;
  fs.writeFileSync(path.join(outDir, 'tokens.css'), css);

  if (utilityRules.size) {
    fs.writeFileSync(
      path.join(outDir, 'typography.css'),
      `/* Generated by design-bridge. Do not edit by hand. */\n${[...utilityRules.values()].join('\n')}`,
    );
  }

  console.log(`Built ${files.length} token file(s) into ${path.relative(process.cwd(), outDir)}.`);
}

const { command, flags } = parseArgs(process.argv.slice(2));
try {
  if (command === 'pull') await pull(flags);
  else if (command === 'build') build(flags);
  else {
    console.log('Usage: design-bridge-tokens <pull|build> [--file key] [--in dir] [--out dir] [--prefix ds] [--no-styles]');
    process.exit(command ? 1 : 0);
  }
} catch (error) {
  console.error(`design-bridge-tokens: ${error.message}`);
  process.exit(1);
}
