import test from 'node:test';
import assert from 'node:assert/strict';
import { toCss, toScss, toTypeScript, toFlatJson } from '../src/build.mjs';

const tree = {
  palette: { blue: { 500: { $type: 'color', $value: '#1c4fd9', $description: 'Brand blue' } } },
  semantic: { action: { $type: 'color', $value: '{palette.blue.500}' } },
  spacing: { md: { $type: 'number', $value: 16 } },
};

test('toCss keeps aliases as var() so themes cascade', () => {
  const css = toCss(tree);
  assert.match(css, /--palette-blue-500: #1c4fd9;/);
  assert.match(css, /--semantic-action: var\(--palette-blue-500\);/);
  assert.match(css, /--spacing-md: 16px;/);
});

test('toCss honours selector and prefix', () => {
  const css = toCss(tree, { selector: ':root[data-theme="dark"]', prefix: 'ds' });
  assert.match(css, /^\/\* Generated by design-bridge[^\n]*\n:root\[data-theme="dark"\] \{/m);
  assert.match(css, /--ds-palette-blue-500:/);
  assert.match(css, /--ds-semantic-action: var\(--ds-palette-blue-500\);/);
});

test('toCss emits descriptions as comments', () => {
  assert.match(toCss(tree), /\/\* Brand blue \*\//);
});

test('toScss resolves aliases because Sass cannot follow var()', () => {
  const scss = toScss(tree);
  assert.match(scss, /\$semantic-action: #1c4fd9;/);
  assert.doesNotMatch(scss, /var\(/);
});

test('toTypeScript points at CSS variables, not literals', () => {
  const ts = toTypeScript(tree, { prefix: 'ds' });
  assert.match(ts, /paletteBlue500: 'var\(--ds-palette-blue-500\)'/);
  assert.match(ts, /export type TokenName = keyof typeof tokens;/);
  assert.match(ts, /\/\*\* Brand blue \*\//);
});

test('toFlatJson produces a resolved name -> value map', () => {
  const flat = JSON.parse(toFlatJson(tree));
  assert.deepEqual(flat, {
    'palette-blue-500': '#1c4fd9',
    'semantic-action': '#1c4fd9',
    'spacing-md': '16px',
  });
});
