blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/gitsual/design-bridge/discussions
    about: Ask a question or discuss an idea before it's a bug report or feature request.
