/**
 * Angular story emitter (`@storybook/angular`).
 *
 * Two differences from Vue that the generated code has to respect:
 *
 * 1. Projected content is `<ng-content>`, not a slot, so a variant with content
 *    needs a `render` returning a `template` — `args` alone cannot express it.
 * 2. `Meta`/`StoryObj` are parameterised by the component class itself, not by
 *    `typeof Component`, because Angular components are classes.
 */

import { exportName, storyTitle, literal, indentBlock } from '../naming.mjs';
import { toArgTypes } from '../argtypes.mjs';

const FIGMA_ROOT = '[data-figma-root]';

/** `{ variant: 'primary', disabled: true }` -> `[variant]="variant" [disabled]="disabled"`. */
function propertyBindings(props = {}) {
  return Object.keys(props)
    .map((key) => `[${key}]="${key}"`)
    .join(' ');
}

export function renderStoryFile({ registry, component }) {
  const { import: imp } = component;
  const symbol = imp.symbol === 'default' ? component.name : imp.symbol;
  const importLine = imp.symbol === 'default'
    ? `import ${symbol} from '${imp.module}';`
    : `import { ${symbol} } from '${imp.module}';`;

  const selector = component.selector ?? null;
  const variants = component.variants?.length
    ? component.variants
    : [{ label: 'Default', props: {} }];

  const stories = variants.map((variant) => {
    const name = exportName(variant.label);
    const args = indentBlock(literal(variant.props ?? {}), 2);
    // Content projection needs a real selector; without one we cannot write a
    // template, so we degrade to args rather than emit a broken story.
    if (!variant.slot || !selector) {
      return `export const ${name}: Story = {\n  name: ${JSON.stringify(variant.label)},\n  args: ${args},\n};`;
    }
    const bindings = propertyBindings(variant.props);
    const open = bindings ? `<${selector} ${bindings}>` : `<${selector}>`;
    return [
      `export const ${name}: Story = {`,
      `  name: ${JSON.stringify(variant.label)},`,
      `  args: ${args},`,
      '  render: (args) => ({',
      '    props: args,',
      `    template: \`<div data-figma-root>${open}${variant.slot}</${selector}></div>\`,`,
      '  }),',
      '};',
    ].join('\n');
  });

  return [
    '// Generated by design-bridge. Do not edit by hand.',
    "import type { Meta, StoryObj } from '@storybook/angular';",
    importLine,
    '',
    `const meta: Meta<${symbol}> = {`,
    `  title: ${JSON.stringify(storyTitle(registry.name, component))},`,
    `  component: ${symbol},`,
    "  tags: ['autodocs'],",
    `  argTypes: ${indentBlock(literal(toArgTypes(component.controls)), 2)},`,
    '  parameters: {',
    `    s2d: { type: 'component', initArgs: { ':selector': ${JSON.stringify(FIGMA_ROOT)}, ':width': 'auto', ':height': 'auto' } },`,
    `    designBridge: { id: ${JSON.stringify(component.id)}, family: ${JSON.stringify(component.family)} },`,
    '  },',
    '};',
    '',
    'export default meta;',
    `type Story = StoryObj<${symbol}>;`,
    '',
    stories.join('\n\n'),
    '',
  ].join('\n');
}
