/**
 * Vue 3 story emitter (`@storybook/vue3-vite`).
 *
 * Variants with slot content cannot use plain `args`, because a slot is not a
 * prop. Those stories get an explicit `render` that mounts the component with
 * the slot filled in; prop-only variants stay on `args` so Storybook controls
 * keep working.
 */

import { exportName, storyTitle, literal, indentBlock } from '../naming.mjs';
import { toArgTypes } from '../argtypes.mjs';

const FIGMA_ROOT = '[data-figma-root]';

export function renderStoryFile({ registry, component }) {
  const { import: imp } = component;
  const symbol = imp.symbol === 'default' ? component.name : imp.symbol;
  const importLine = imp.symbol === 'default'
    ? `import ${symbol} from '${imp.module}';`
    : `import { ${symbol} } from '${imp.module}';`;

  const variants = component.variants?.length
    ? component.variants
    : [{ label: 'Default', props: {} }];

  const stories = variants.map((variant) => {
    const name = exportName(variant.label);
    const args = indentBlock(literal(variant.props ?? {}), 2);
    if (!variant.slot) {
      return `export const ${name}: Story = {\n  name: ${JSON.stringify(variant.label)},\n  args: ${args},\n};`;
    }
    // `setup` exposes args to the template; the wrapper div is what
    // story.to.design captures as the component boundary.
    return [
      `export const ${name}: Story = {`,
      `  name: ${JSON.stringify(variant.label)},`,
      `  args: ${args},`,
      '  render: (args) => ({',
      `    components: { ${symbol} },`,
      '    setup: () => ({ args }),',
      `    template: \`<div data-figma-root><${symbol} v-bind="args">${variant.slot}</${symbol}></div>\`,`,
      '  }),',
      '};',
    ].join('\n');
  });

  return [
    '// Generated by design-bridge. Do not edit by hand.',
    "import type { Meta, StoryObj } from '@storybook/vue3-vite';",
    importLine,
    '',
    `const meta: Meta<typeof ${symbol}> = {`,
    `  title: ${JSON.stringify(storyTitle(registry.name, component))},`,
    `  component: ${symbol},`,
    "  tags: ['autodocs'],",
    `  argTypes: ${indentBlock(literal(toArgTypes(component.controls)), 2)},`,
    '  parameters: {',
    `    s2d: { type: 'component', initArgs: { ':selector': ${JSON.stringify(FIGMA_ROOT)}, ':width': 'auto', ':height': 'auto' } },`,
    `    designBridge: { id: ${JSON.stringify(component.id)}, family: ${JSON.stringify(component.family)} },`,
    '  },',
    '};',
    '',
    'export default meta;',
    `type Story = StoryObj<typeof ${symbol}>;`,
    '',
    stories.join('\n\n'),
    '',
  ].join('\n');
}
